apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: efk-logging
  namespace: kube-system
  labels:
    k8s-app: efk-logging
#    kubernetes.io/cluster-service: "true"
    version: v1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: efk-logging
      version: v1.0.0
  template:
    metadata:
      labels:
        k8s-app: efk-logging
        version: v1.0.0
    spec:
#      serviceAccountName: heapster
      containers:
        - image: elasticsearch:2.4
          name: elasticsearch
#          resources:
#            # keep request = limit to keep this container in guaranteed class
#            limits:
#              cpu: 100m
#              memory: {{ metrics_memory }}
#            requests:
#              cpu: 100m
#              memory: {{ metrics_memory }}
#          command:
#            - elasticsearch
#            - -Des.network.host=0.0.0.0
          ports:
          - containerPort: 9200
            name: db
            protocol: TCP
          - containerPort: 9300
            name: transport
            protocol: TCP
#          volumeMounts:
#            - name: es-persistent-storage
#              mountPath: /data
#        - image: kibana:5.0.0-alpha5
        - image: hleon256/kibana:latest
          name: kibana
#          env:
#            - name: ELASTICSEARCH_URL
#              value: http://$(LOGGING_ELASTICSEARCH_SERVICE_HOST):$(LOGGING_ELASTICSEARCH_SERVICE_PORT)
          ports:
          - containerPort: 5601
            name: ui
            protocol: TCP
          command: ["/bin/sh", "-c"]
          args: ["MYVARS='$LOGGING_ELASTICSEARCH_SERVICE_HOST:$LOGGING_ELASTICSEARCH_SERVICE_PORT';envsubst \"$MYVARS\" < /opt/kibana/config/kibana.yml.template > /opt/kibana/config/kibana.yml;/tmp/entrypoint.sh"]
        - image: hleon256/fluentd:latest 
          name: fluentd
          ports:
          - containerPort: 24224
            protocol: TCP
          - containerPort: 5140
            protocol: UDP
          command: ["/bin/sh", "-c"]
          args: ["MYVARS='$LOGGING_ELASTICSEARCH_SERVICE_HOST:$LOGGING_ELASTICSEARCH_SERVICE_PORT';envsubst \"$MYVARS\" < /fluentd/etc/fluent.conf.template > /fluentd/etc/$FLUENTD_CONF;exec fluentd -c /fluentd/etc/$FLUENTD_CONF -p /fluentd/plugins $FLUENTD_OPT"]
#          volumeMounts:
#            - name: fluentd-persistent-storage
#              mountPath: /fluentd/log
#            - name: fluent-conf
#              mountPath: /fluentd/etc
#      volumes:
#      - name: fluent-conf
#        configMap:
#          name: fluent-configmap
#          items:
#          - key: fluent.conf
#            path: fluent.conf
#      - name: fluentd-persistent-storage
##        emptyDir: {}
#        glusterfs:
#          endpoints: glusterfs-efk
#          path: fluentd
#      - name: es-persistent-storage
##        emptyDir: {}
#        glusterfs:
#          endpoints: glusterfs-efk
#          path: elasticsearch
